### ISSUE TITLE
Bugs for _pre6_vcf2plink process

### ISSUE THREAD

**Issue by wang-tianpeng** [jbv2/nf-vcf2treemix#1]
It is a great pipeline! I find it super useful to perform the treemix analysis. 
Here I want to have a suggestion. For the plants or the non-human reference genome, it needs to add the parameter"--allow-extra-chr" in the plink converting process, otherwise, it will report the errors.

**Comment by jbv2** [comment]
Oh hey, you'll find this #enhancement in the latest commit. Thank you.
