### ISSUE TITLE
Rename workflow file to main.nf

### ISSUE THREAD

**Issue by jashgopani** [jbv2/nf-vcf2treemix#2]
Hi,
Can you please rename the workflow file vcf2treemix.nf to main.nf? I am trying to add this pipeline to the seqera workspace but the platform requires the pipeline repo to have a main.nf file.

**Comment by jbv2** [comment]
Hi Jash,
This code was developed in DSL1 from Nextflow. So, even if I rename the pipeline, I am not sure it will continue to be compatible with recent Nextflow versions. 
I think the best to do for using in a Seqera workspace, is to use an nf-core module or sub-workflow. 
https://nf-co.re/docs/contributing/modules

Unfortunately, I can't promise to make it soon as I am no longer using TreeMix at the moment. But, feel free to take this as the skeleton to make a proper DSL2 nf-core module or sub-workflow. I am happy to be one of the reviewers if you open a pull request in nf-core. 
https://nf-co.re/docs/contributing/modules#pr-review-checklist
